### ISSUE TITLE
Difference efficientNMS/yoloNMS VS NvDsInferYolo

### ISSUE THREAD

**Issue by siretru** [levipereira/deepstream-yolo-e2e#1]
Hello,

First of all, thank you for all these repositories. The work accomplished is just great.

I would like to ask you 1 question: 

-I'm having trouble understanding the difference between the efficientNMS/yoloNMS plugin (needed to build the .engine file and make inferences) and the NvDsInferYolo parse function?

Thank you !

**Comment by levipereira** [comment]
https://github.com/levipereira/deepstream-yolo-e2e/issues/2#issuecomment-2186780507
