### ISSUE TITLE
can this project use models deployed with triton?

### ISSUE THREAD

**Issue by jaffe-fly** [levipereira/deepstream-yolo-e2e#15]
after use `process_onnx` get `yolov8x-trt-fp16-netsize-640-batch-1.engine` model,
how to deply it in triton ?
how to configure it in deepstream?

 i will also share my some settings after study it

**Comment by levipereira** [comment]
You can use this two repo as example
https://github.com/levipereira/deepstream-yolo-triton-server-rtsp-out
https://github.com/levipereira/triton-server-yolo
Change config-file and change component on pipeline instead use gst-nvinfer use gst-nvinferserver
