### ISSUE TITLE
Can I use the NvDsInferYolo parse function in Deepstream for a YoloV8 model built with yoloNMS?

### ISSUE THREAD

**Issue by siretru** [levipereira/deepstream-yolo-e2e#2]
Hello,

First of all, thank you for all these repositories. The work accomplished is just great.

I would like to ask you 1 question:

-Can I use the NvDsInferYolo parse function in Deepstream for a YoloV8 model built with yoloNMS?

Thank you !

**Comment by levipereira** [comment]
The yoloNMS plugin has been renamed to EfficientNMSX to facilitate integration with TensorRT. For detection models, I use EfficientNMS, and for segmentation models, I use EfficientNMSX (formerly yoloNMS) and the roiAlign plugin.

Both plugins are supported by NvDsInferYolo.

The export of the model in End2End format is implemented in this repository: https://github.com/levipereira/ultralytics
