### ISSUE TITLE
How to support int8?

### ISSUE THREAD

**Issue by tms2003** [levipereira/deepstream-yolo-e2e#5]
I configured 
```
network-mode=1 

int8-calib-file=calib.table
```
in config_pgie_yolo_det.txt
, but it doesn't work. There is no int8 option in -p parameter. How to support int8? I use yolov8

**Comment by levipereira** [comment]
> I configured
> 
> ```
> network-mode=1 
> 
> int8-calib-file=calib.table
> ```
> 
> in config_pgie_yolo_det.txt , but it doesn't work. There is no int8 option in -p parameter. How to support int8? I use yolov8

you need quantize your model to use this option.
NVIDIA released this recently.
https://nvidia.github.io/TensorRT-Model-Optimizer/guides/_onnx_quantization.html
