### ISSUE TITLE
ERROR from src_bin_muxer

### ISSUE THREAD

**Issue by osmancanaksoy** [levipereira/deepstream-yolo-e2e#6]
deepstream-app -c deepstream_yolo_det.ini
** ERROR: <main:706>: Failed to set pipeline to PAUSED
Quitting
ERROR from src_bin_muxer: Output width not set
Debug info: gstnvstreammux.cpp(3128): gst_nvstreammux_change_state (): /GstPipeline:pipeline/GstBin:multi_src_bin/GstNvStreamMux:src_bin_muxer
App run failed

**Comment by levipereira** [comment]
This error was caused by renaming the file from deepstream_yolo_det.txt to deepstream_yolo_det.ini. I've already fixed the issue. Please let me know if there are any further problems.
